version: '3'
services:
  postgresdb:
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    container_name: tuum-api-db
    environment:
      POSTGRES_DB: "tuum_bank_data"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    networks:
      - tuum-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tuum-api-rabbitmq
    healthcheck:
      test: ["CMD", "sleep", "5"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tuum-network

  app:
    build:
      context: .
    container_name: tuum-api
    ports:
      - "8091:8080"
    depends_on:
      - postgresdb
      - rabbitmq
    networks:
      - tuum-network

networks:
  tuum-network:
    driver: bridge
    ipam:
      driver: default
