version: '3'
services:
  postgresdb:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: "postgres:latest"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    container_name: tuum-api-db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: tuum-api
    ports:
      - "8091:8080"
    depends_on:
      - postgresdb
    networks:
      - default
    links:
      - "postgresdb"
